# Generated by Django 3.1.7 on 2021-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, upload_to='db.sqlite3')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'QUEEN'), ('KIN', 'KING'), ('YAC', 'AC'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
