# Generated by Django 3.1.7 on 2021-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_auto_20210404_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('KIN', 'KING'), ('NAC', 'NON-AC'), ('YAC', 'AC'), ('QUE', 'QUEEN')], max_length=3),
        ),
    ]
