# Generated by Django 3.1.7 on 2021-03-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210322_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='numbers',
            new_name='number',
        ),
    ]
