# Generated by Django 3.1.7 on 2021-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20210405_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC'), ('QUE', 'QUEEN'), ('KIN', 'KING')], max_length=3),
        ),
    ]
