# Generated by Django 3.1.7 on 2021-03-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210322_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='roomnumber',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('NAC', 'NON-AC'), ('KIN', 'KING'), ('QUE', 'QUEEN'), ('YAC', 'AC')], max_length=3),
        ),
    ]
