# Generated by Django 3.1.7 on 2021-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20210322_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'QUEEN'), ('KIN', 'KING'), ('NAC', 'NON-AC'), ('YAC', 'AC')], max_length=3),
        ),
    ]
