# Generated by Django 3.1.7 on 2021-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20210323_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC'), ('QUE', 'QUEEN'), ('KIN', 'KING')], max_length=3),
        ),
    ]
