# Generated by Django 3.1.7 on 2021-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20210329_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('KIN', 'KING'), ('NAC', 'NON-AC'), ('QUE', 'QUEEN')], max_length=3),
        ),
    ]
