# Generated by Django 3.1.7 on 2021-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20210329_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('QUE', 'QUEEN'), ('KIN', 'KING'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
