# Generated by Django 3.1.7 on 2021-04-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_auto_20210402_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('KIN', 'KING'), ('QUE', 'QUEEN'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
