# Generated by Django 3.1.7 on 2021-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_auto_20210403_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('NAC', 'NON-AC'), ('YAC', 'AC'), ('QUE', 'QUEEN'), ('KIN', 'KING')], max_length=3),
        ),
    ]
