# Generated by Django 3.1.7 on 2021-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_auto_20210404_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('KIN', 'KING'), ('YAC', 'AC'), ('QUE', 'QUEEN'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
