# Generated by Django 3.1.7 on 2021-04-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_auto_20210404_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('KIN', 'KING'), ('QUE', 'QUEEN'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
