# Generated by Django 3.1.7 on 2021-04-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_auto_20210404_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('KIN', 'KING'), ('YAC', 'AC'), ('NAC', 'NON-AC'), ('QUE', 'QUEEN')], max_length=3),
        ),
    ]
