# Generated by Django 3.1.7 on 2021-04-04 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_auto_20210404_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotelnumber',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('KIN', 'KING'), ('NAC', 'NON-AC'), ('QUE', 'QUEEN')], max_length=3),
        ),
    ]
