# Generated by Django 3.1.7 on 2021-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0026_auto_20210404_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'QUEEN'), ('NAC', 'NON-AC'), ('KIN', 'KING'), ('YAC', 'AC')], max_length=3),
        ),
    ]
