# Generated by Django 3.1.7 on 2021-04-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0027_auto_20210404_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC'), ('QUE', 'QUEEN'), ('KIN', 'KING')], max_length=3),
        ),
    ]
