# Generated by Django 3.1.7 on 2021-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0029_auto_20210404_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'QUEEN'), ('YAC', 'AC'), ('NAC', 'NON-AC'), ('KIN', 'KING')], max_length=3),
        ),
    ]
