# Generated by Django 3.1.7 on 2021-04-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0031_auto_20210404_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('NAC', 'NON-AC'), ('KIN', 'KING'), ('QUE', 'QUEEN'), ('YAC', 'AC')], max_length=3),
        ),
    ]
