# Generated by Django 3.1.7 on 2021-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0036_auto_20210404_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('NAC', 'NON-AC'), ('QUE', 'QUEEN'), ('KIN', 'KING'), ('YAC', 'AC')], max_length=3),
        ),
    ]
