# Generated by Django 3.1.7 on 2021-04-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0038_auto_20210404_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'QUEEN'), ('KIN', 'KING'), ('YAC', 'AC'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
