# Generated by Django 3.1.7 on 2021-04-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'QUEEN'), ('YAC', 'AC'), ('NAC', 'NON-AC'), ('KIN', 'KING')], max_length=3),
        ),
    ]
