# Generated by Django 3.1.7 on 2021-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_auto_20210412_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='slug',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'QUEEN'), ('KIN', 'KING'), ('YAC', 'AC'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
