# Generated by Django 3.2 on 2021-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('QUE', 'QUEEN'), ('NAC', 'NON-AC'), ('KIN', 'KING')], max_length=3),
        ),
    ]
