# Generated by Django 3.1.7 on 2021-04-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_auto_20210415_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
