# Generated by Django 3.2 on 2021-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('Contactnumber', models.TextField(max_length=10)),
                ('subject', models.TextField()),
            ],
        ),
    ]
