# Generated by Django 3.1.7 on 2021-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_auto_20210406_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('KIN', 'KING'), ('YAC', 'AC'), ('QUE', 'QUEEN'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
