# Generated by Django 3.2 on 2021-05-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_alter_contact_contactnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Contactnumber',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
