# Generated by Django 3.2 on 2021-05-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_auto_20210510_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
