# Generated by Django 3.2 on 2021-05-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0009_foodimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodimage',
            old_name='description',
            new_name='price',
        ),
    ]
