# Generated by Django 3.2 on 2021-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0010_rename_description_foodimage_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='description',
            new_name='descriptio',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
