# Generated by Django 3.2 on 2021-05-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0011_auto_20210513_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='description',
        ),
    ]
