# Generated by Django 3.2 on 2021-05-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0012_remove_foodimage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='descriptio',
            new_name='description',
        ),
    ]
